### ISSUE TITLE
'yarn start' failing to load due unused routes

### ISSUE THREAD

**Issue by ronaldstoner** [indigotheory/decentralized-pandemic-reserve#3]
Fresh pull from git results in the following after running 'yarn' and 'yarn start':
 
Compiled with warnings.

./src/App.js
  Line 13:3:  'Link' is defined but never used                no-unused-vars
  Line 32:7:  'themeName' is assigned a value but never used  no-unused-vars

./src/components/Header.js
  Line 9:5:   'Switch' is defined but never used  no-unused-vars
  Line 10:5:  'Route' is defined but never used   no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Browser is showing the following error:**

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at noopServiceWorkerMiddleware (/home/stoner/Desktop/dpr-hackathon/decentralized-pandemic-reserve/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/home/stoner/Desktop/dpr-hackathon/decentralized-pandemic-reserve/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/stoner/Desktop/dpr-hackathon/decentralized-pandemic-reserve/node_modules/express/lib/router/index.js:317:13)
    at /home/stoner/Desktop/dpr-hackathon/decentralized-pandemic-reserve/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/stoner/Desktop/dpr-hackathon/decentralized-pandemic-reserve/node_modules/express/lib/router/index.js:335:12)
    at next (/home/stoner/Desktop/dpr-hackathon/decentralized-pandemic-reserve/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/home/stoner/Desktop/dpr-hackathon/decentralized-pandemic-reserve/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/home/stoner/Desktop/dpr-hackathon/decentralized-pandemic-reserve/node_modules/express/lib/router/layer.js:95:5)

**Comment by ronaldstoner** [comment]
Commenting out the lines seems to fix the eslint warnings. 

Line 13:3: 'Link' is defined but never used no-unused-vars
Line 32:7: 'themeName' is assigned a value but never used no-unused-vars
Line 9:5: 'Switch' is defined but never used no-unused-vars
Line 10:5: 'Route' is defined but never used no-unused-vars

In regards to the browser error, 'npm audit' found a ton of vulnerabilities. Running 'npm audit fix' resolved most of these issues, and allowed me to start the local development server. Onward!

**Comment by wfsterling** [comment]
use npm.
